// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as Utils from "../../../lib/utils";
import * as ClassVarianceAuthority from "class-variance-authority";

function cn(prim) {
  return Utils.cn(prim);
}

var variants = ClassVarianceAuthority.cva("inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50", {
      variants: {
        variant: {
          default: "bg-primary text-primary-foreground shadow hover:bg-primary/90",
          destructive: "bg-destructive text-destructive-foreground shadow-sm hover:bg-destructive/90",
          outline: "border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground",
          secondary: "bg-secondary text-secondary-foreground shadow-sm hover:bg-secondary/80",
          ghost: "hover:bg-accent hover:text-accent-foreground",
          link: "text-primary underline-offset-4 hover:underline"
        },
        size: {
          default: "h-9 px-4 py-2",
          sm: "h-8 rounded-md px-3 text-xs",
          lg: "h-10 rounded-md px-8",
          icon: "h-9 w-9"
        }
      },
      defaultVariants: {
        variant: "default",
        size: "default"
      }
    });

var ButtonVariants = {
  variants: variants
};

function Button$Make(props) {
  var __variant = props.variant;
  var variant = __variant !== undefined ? __variant : "default";
  return JsxRuntime.jsx("button", {
              children: props.children,
              className: Utils.cn([variants(variant)])
            });
}

var Make = {
  make: Button$Make
};

export {
  cn ,
  ButtonVariants ,
  Make ,
}
/* variants Not a pure module */
