-- AlterTable
ALTER TABLE "DeliveryCity" ALTER COLUMN "shipping_fees" SET DEFAULT 0,
ALTER COLUMN "shipping_fees" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "OrderProduct" ALTER COLUMN "price" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "sale" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "purchase_price" SET DEFAULT 0,
ALTER COLUMN "purchase_price" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "selling_price" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "sale" SET DEFAULT 0,
ALTER COLUMN "sale" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "ProductPricingAdjustment" ALTER COLUMN "value" SET DEFAULT 0,
ALTER COLUMN "value" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "ProductVariantCombination" ALTER COLUMN "purchase_price" SET DEFAULT 0,
ALTER COLUMN "purchase_price" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "selling_price" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "sale" SET DEFAULT 0,
ALTER COLUMN "sale" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "caution" SET DEFAULT 0,
ALTER COLUMN "caution" SET DATA TYPE DECIMAL(65,30);
