// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Utils from "../../../lib/utils";

function cn(prim) {
  return Utils.cn(prim);
}

function Card$Card(props) {
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: "rounded-xl border bg-card text-card-foreground shadow"
            });
}

var Card = {
  make: Card$Card
};

function Card$CardHeader(props) {
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: "flex flex-col space-y-1.5 p-6"
            });
}

var CardHeader = {
  make: Card$CardHeader
};

function Card$CardTitle(props) {
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: "font-semibold leading-none tracking-tight"
            });
}

var CardTitle = {
  make: Card$CardTitle
};

function Card$CardDescription(props) {
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: "text-sm text-muted-foreground"
            });
}

var CardDescription = {
  make: Card$CardDescription
};

function Card$CardContent(props) {
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: "p-6 pt-0"
            });
}

var CardContent = {
  make: Card$CardContent
};

function Card$CardFooter(props) {
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: "flex items-center p-6 pt-0"
            });
}

var CardFooter = {
  make: Card$CardFooter
};

function Card$Make(props) {
  var footer = props.footer;
  var description = props.description;
  var title = props.title;
  return JsxRuntime.jsxs(Card$Card, {
              children: [
                JsxRuntime.jsxs(Card$CardHeader, {
                      children: [
                        title !== undefined ? JsxRuntime.jsx(Card$CardTitle, {
                                children: title
                              }) : null,
                        description !== undefined ? JsxRuntime.jsx(Card$CardDescription, {
                                children: description
                              }) : null
                      ]
                    }),
                JsxRuntime.jsx(Card$CardContent, {
                      children: props.content
                    }),
                footer !== undefined ? JsxRuntime.jsx(Card$CardFooter, {
                        children: Caml_option.valFromOption(footer)
                      }) : null
              ]
            });
}

var Make = {
  make: Card$Make
};

export {
  cn ,
  Card ,
  CardHeader ,
  CardTitle ,
  CardDescription ,
  CardContent ,
  CardFooter ,
  Make ,
}
/* react/jsx-runtime Not a pure module */
