// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as Utils from "../../../lib/utils";
import * as ReactAlertDialog from "@radix-ui/react-alert-dialog";

function cn(prim) {
  return Utils.cn(prim);
}

var AlertDialog = {};

var AlertDialogTrigger = {};

var AlertDialogPortal = {};

var AlertDialogOverlay = {};

var AlertDialogContent = {};

var AlertDialogTitle = {};

var AlertDialogDescription = {};

var AlertDialogAction = {};

var AlertDialogCancel = {};

function AlertDialog$Make(props) {
  return JsxRuntime.jsxs(ReactAlertDialog.Root, {
              children: [
                JsxRuntime.jsx(ReactAlertDialog.Trigger, {
                      asChild: true,
                      children: props.trigger
                    }),
                JsxRuntime.jsxs(ReactAlertDialog.Portal, {
                      children: [
                        JsxRuntime.jsx(ReactAlertDialog.Overlay, {
                              className: Utils.cn(["fixed inset-0 z-50 bg-black/80 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0"])
                            }),
                        JsxRuntime.jsxs(ReactAlertDialog.Content, {
                              className: Utils.cn(["fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] sm:rounded-lg"]),
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(ReactAlertDialog.Title, {
                                              className: Utils.cn(["text-lg font-semibold"]),
                                              children: props.title
                                            }),
                                        JsxRuntime.jsx(ReactAlertDialog.Description, {
                                              className: Utils.cn(["text-sm text-muted-foreground"]),
                                              children: props.description
                                            })
                                      ],
                                      className: Utils.cn(["flex flex-col space-y-2 text-center sm:text-left"])
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(ReactAlertDialog.Cancel, {
                                              className: Utils.cn([""]),
                                              children: props.cancel
                                            }),
                                        JsxRuntime.jsx(ReactAlertDialog.Action, {
                                              className: Utils.cn([""]),
                                              children: props.continue
                                            })
                                      ],
                                      className: Utils.cn(["flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2"])
                                    })
                              ]
                            })
                      ]
                    })
              ]
            });
}

var Make = {
  make: AlertDialog$Make
};

export {
  cn ,
  AlertDialog ,
  AlertDialogTrigger ,
  AlertDialogPortal ,
  AlertDialogOverlay ,
  AlertDialogContent ,
  AlertDialogTitle ,
  AlertDialogDescription ,
  AlertDialogAction ,
  AlertDialogCancel ,
  Make ,
}
/* react/jsx-runtime Not a pure module */
