// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Utils from "../../../lib/utils";
import ReactSlot from "@radix-ui/react-slot";
import * as ReactIcons from "@radix-ui/react-icons";

function cn(prim) {
  return Utils.cn(prim);
}

var ChevronRightIcon = {};

var DotsHorizontalIcon = {};

var Slot = {};

function Breadcrumb$Breadcrumb(props) {
  return JsxRuntime.jsx("nav", {
              children: props.children
            });
}

var Breadcrumb = {
  make: Breadcrumb$Breadcrumb
};

function Breadcrumb$BreadcrumbList(props) {
  return JsxRuntime.jsx("ol", {
              children: props.children,
              className: Utils.cn(["flex flex-wrap items-center gap-1.5 break-words text-sm text-muted-foreground sm:gap-2.5"])
            });
}

var BreadcrumbList = {
  make: Breadcrumb$BreadcrumbList
};

function Breadcrumb$BreadcrumbItem(props) {
  return JsxRuntime.jsx("li", {
              children: props.children,
              className: Utils.cn(["inline-flex items-center gap-1.5"])
            });
}

var BreadcrumbItem = {
  make: Breadcrumb$BreadcrumbItem
};

function Breadcrumb$BreadcrumbLink(props) {
  return JsxRuntime.jsx(ReactSlot, {
              className: Utils.cn(["transition-colors hover:text-foreground"])
            });
}

var BreadcrumbLink = {
  make: Breadcrumb$BreadcrumbLink
};

function Breadcrumb$BreadcrumbPage(props) {
  return JsxRuntime.jsx("span", {
              children: props.children,
              className: Utils.cn(["font-normal text-foreground"]),
              role: "link"
            });
}

var BreadcrumbPage = {
  make: Breadcrumb$BreadcrumbPage
};

function Breadcrumb$BreadcrumbSeparator(props) {
  var children = props.children;
  return JsxRuntime.jsx("li", {
              children: children !== undefined ? Caml_option.valFromOption(children) : JsxRuntime.jsx(ReactIcons.ChevronRightIcon, {}),
              className: Utils.cn(["[&>svg]:size-3.5"]),
              role: "presentation"
            });
}

var BreadcrumbSeparator = {
  make: Breadcrumb$BreadcrumbSeparator
};

function Breadcrumb$BreadcrumbEllipsis(props) {
  return JsxRuntime.jsxs("span", {
              children: [
                JsxRuntime.jsx(ReactIcons.DotsHorizontalIcon, {
                      className: "h-4 w-4"
                    }),
                JsxRuntime.jsx("span", {
                      children: "More",
                      className: "sr-only"
                    })
              ],
              className: Utils.cn(["flex h-9 w-9 items-center justify-center"]),
              role: "presentation"
            });
}

var BreadcrumbEllipsis = {
  make: Breadcrumb$BreadcrumbEllipsis
};

export {
  cn ,
  ChevronRightIcon ,
  DotsHorizontalIcon ,
  Slot ,
  Breadcrumb ,
  BreadcrumbList ,
  BreadcrumbItem ,
  BreadcrumbLink ,
  BreadcrumbPage ,
  BreadcrumbSeparator ,
  BreadcrumbEllipsis ,
}
/* react/jsx-runtime Not a pure module */
