// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Utils from "../../../lib/utils";
import * as ReactLabel from "@radix-ui/react-label";

function cn(prim) {
  return Utils.cn(prim);
}

var Root = {};

var make = React.forwardRef(function (props, ref) {
      var __htmlFor = props.htmlFor;
      var __children = props.children;
      var __className = props.className;
      var className = __className !== undefined ? __className : "";
      var children = __children !== undefined ? Caml_option.valFromOption(__children) : null;
      var htmlFor = __htmlFor !== undefined ? __htmlFor : "";
      return JsxRuntime.jsx(ReactLabel.Root, {
                  className: className,
                  children: children,
                  htmlFor: htmlFor,
                  ref: Core__Option.map((ref == null) ? undefined : Caml_option.some(ref), (function (prim) {
                          return prim;
                        }))
                });
    });

export {
  cn ,
  Root ,
  make ,
}
/* make Not a pure module */
