// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as Utils from "../../../lib/utils";
import * as ReactAvatar from "@radix-ui/react-avatar";

function cn(prim) {
  return Utils.cn(prim);
}

var Avatar = {};

var AvatarImage = {};

var AvatarFallback = {};

function Avatar$Make(props) {
  return JsxRuntime.jsxs(ReactAvatar.Root, {
              className: Utils.cn(["relative flex h-10 w-10 shrink-0 overflow-hidden rounded-full"]),
              children: [
                JsxRuntime.jsx(ReactAvatar.Image, {
                      className: Utils.cn(["aspect-square h-full w-full"]),
                      src: props.src,
                      alt: props.alt
                    }),
                JsxRuntime.jsx(ReactAvatar.Fallback, {
                      className: Utils.cn(["flex h-full w-full items-center justify-center rounded-full bg-muted"]),
                      children: props.fallback
                    })
              ]
            });
}

var Make = {
  make: Avatar$Make
};

export {
  cn ,
  Avatar ,
  AvatarImage ,
  AvatarFallback ,
  Make ,
}
/* react/jsx-runtime Not a pure module */
