// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as Utils from "../../../lib/utils";
import * as ClassVarianceAuthority from "class-variance-authority";

function cn(prim) {
  return Utils.cn(prim);
}

var variants = ClassVarianceAuthority.cva("inline-flex items-center rounded-md border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2", {
      variants: {
        variant: {
          default: "border-transparent bg-primary text-primary-foreground shadow hover:bg-primary/80",
          secondary: "border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80",
          destructive: "border-transparent bg-destructive text-destructive-foreground shadow hover:bg-destructive/80",
          outline: "text-foreground"
        }
      },
      defaultVariants: {
        variant: "default"
      }
    });

var BadgeVariants = {
  variants: variants
};

function Badge$Make(props) {
  var __variant = props.variant;
  var variant = __variant !== undefined ? __variant : "default";
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: Utils.cn([variants(variant)])
            });
}

var Make = {
  make: Badge$Make
};

export {
  cn ,
  BadgeVariants ,
  Make ,
}
/* variants Not a pure module */
